### ISSUE TITLE
Refactor Generator

### ISSUE THREAD

**Issue by JunaMeinhold** [JunaMeinhold/HexaGen#18]
- [ ] Clean the generation process
- [ ] Comment code that needs explanation

### Task breakdown
- [ ] Refactor COM function generator
- [ ] Refactor COM constant generator
- [ ] Refactor COM enum generator
- [ ] Refactor COM struct generator
- [ ] Refactor COM handle generator
- [ ] Refactor COM extensions generator
- [ ] Refactor function generator
- [ ] Refactor constant generator
- [ ] Refactor enum generator
- [ ] Refactor struct generator
- [ ] Refactor handle generator
- [ ] Refactor extensions generator
- [ ] Refactor settings, helpers and extensions
